FROM golang:1.26-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/producer ./cmd/producer

FROM alpine:3.19

RUN apk add --no-cache ca-certificates && \
    adduser -D -u 65532 appuser

WORKDIR /app

COPY --from=builder /app/producer .
COPY config.yaml .

USER 65532

ENTRYPOINT ["/app/producer"]
