FROM busybox:1.36.1-glibc AS tools
FROM otel/opentelemetry-collector-contrib:0.122.0

# Add wget (from busybox) and required glibc libraries for healthcheck support
COPY --from=tools /bin/busybox /bin/wget
COPY --from=tools /lib/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=tools /lib/libc.so.6 /lib/
COPY --from=tools /lib/libm.so.6 /lib/
COPY --from=tools /lib/libresolv.so.2 /lib/
COPY --from=tools /lib/libpthread.so.0 /lib/
COPY --from=tools /lib/libnss_dns.so.2 /lib/
COPY --from=tools /lib/libnss_files.so.2 /lib/

EXPOSE 4317 4318 8888 8889 13133

ENTRYPOINT ["/otelcol-contrib"]
